### PR TITLE
Fix the binding initializing logic to correctly detect repeated tensors

### PR DESCRIPTION
**Pull request by tanmayv25**

### CODE REVIEW

**Review by deadeyegoodwin — APPROVED** [review]

**Review by CoderHam — APPROVED** [review]

**Comment by deadeyegoodwin** [comment]
@tanmayv25  Does this need to go in 21.11?

**Comment by tanmayv25** [comment]
Yes.. It is needed for TRT models with shape tensor I/O.

**Comment by deadeyegoodwin** [comment]
OK, I will cherry-pick it.

**Comment by deadeyegoodwin** [comment]
Sorry, this is already cherry picked. I meant to be asking about https://github.com/triton-inference-server/tensorrt_backend/pull/21

**Pull request merged**
